# Explore here

Read data and display all columns (from csv)

In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
data= pd.read_csv("../data/raw/flights.csv")

In [4]:
import pandas as pd

In [5]:
data.head()

,legId,searchDate,flightDate,startingAirport,destinationAirport,fareBasisCode,travelDuration,elapsedDays,isBasicEconomy,isRefundable,isNonStop,baseFare,totalFare,seatsRemaining,totalTravelDistance,segmentsDepartureTimeEpochSeconds,segmentsDepartureTimeRaw,segmentsArrivalTimeEpochSeconds,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsAirlineCode,segmentsEquipmentDescription,segmentsDurationInSeconds,segmentsDistance,segmentsCabinCode
0,65a8a691c4d77487a439d6f44c219a39,2022-04-17,2022-04-21,LGA,DFW,UA3NA0BQ,PT5H45M,0,True,False,False,110.70,142.6,9,1487.0,1650542400||1650554580,2022-04-21T08:00:00.000-04:00||2022-04-21T11:2...,1650551340||1650563100,2022-04-21T10:29:00.000-04:00||2022-04-21T12:4...,ATL||DFW,LGA||ATL,Delta||Delta,DL||DL,Airbus A321||Airbus A321,8940||8520,762||725,coach||coach
1,1ad3c9a84f803cc98028ba8c67f35941,2022-04-18,2022-04-24,ATL,LGA,H3AHZNN1,PT2H22M,0,False,False,True,450.23,498.6,1,762.0,1650845400,2022-04-24T20:10:00.000-04:00,1650853920,2022-04-24T22:32:00.000-04:00,LGA,ATL,American Airlines,AA,Embraer 170,8520,762,coach
2,510f3a1255b9843a8eae48032b191faf,2022-04-17,2022-04-22,OAK,LAX,YH0OASMR,PT7H11M,0,False,False,False,645.02,717.0,7,1628.0,1650671280||1650688200,2022-04-22T16:48:00.000-07:00||2022-04-22T21:3...,1650678600||1650697140,2022-04-22T18:50:00.000-07:00||2022-04-22T23:5...,SEA||ONT,OAK||SEA,Alaska Airlines||Alaska Airlines,AS||AS,Embraer 175||Airbus A320,7320||8940,672||956,coach||coach
3,ca0fb1ee992f752bbfdcd03a8b3e8ed0,2022-04-17,2022-05-18,LGA,SFO,MAUTA5MC,PT10H22M,0,False,False,False,440.93,497.6,9,2897.0,1652904600||1652923320,2022-05-18T16:10:00.000-04:00||2022-05-18T21:2...,1652914020||1652941920,2022-05-18T18:47:00.000-04:00||2022-05-18T23:3...,ATL||SFO,LGA||ATL,Delta||Delta,DL||DL,Airbus A321||Boeing 757-300,9420||18600,762||2135,coach||coach
4,5f7a29384cea410317ca308d2e065059,2022-04-17,2022-05-06,SFO,BOS,E0AJZNN1,PT8H29M,1,False,False,False,506.05,567.6,3,2751.0,1651899120||1651925100,2022-05-06T21:52:00.000-07:00||2022-05-07T08:0...,1651919400||1651929660,2022-05-07T06:30:00.000-04:00||2022-05-07T09:2...,JFK||BOS,SFO||JFK,JetBlue Airways||JetBlue Airways,B6||B6,Airbus A319-321||AIRBUS INDUSTRIE A321 SHARKLETS,20280||4560,2566||185,coach||coach

In [6]:
data.shape

(4106938, 27)

Save data in a database using sqlite3 (RUN FROM HERE!!!)

In [57]:
import sqlite3
db_con = sqlite3.connect("../data/raw/flight_data.sqlite")
# data.to_sql("raw_data", con=db_con)

In [58]:
import sqlite3
import pandas as pd

data_from_db = pd.read_sql_query('SELECT * from raw_data', db_con)

In [59]:
pd.set_option('display.max_columns', None) #To display all columns

In [60]:
data_from_db.head()

,index,legId,searchDate,flightDate,startingAirport,destinationAirport,fareBasisCode,travelDuration,elapsedDays,isBasicEconomy,isRefundable,isNonStop,baseFare,totalFare,seatsRemaining,totalTravelDistance,segmentsDepartureTimeEpochSeconds,segmentsDepartureTimeRaw,segmentsArrivalTimeEpochSeconds,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsAirlineCode,segmentsEquipmentDescription,segmentsDurationInSeconds,segmentsDistance,segmentsCabinCode
0,0,65a8a691c4d77487a439d6f44c219a39,2022-04-17,2022-04-21,LGA,DFW,UA3NA0BQ,PT5H45M,0,1,0,0,110.70,142.6,9,1487.0,1650542400||1650554580,2022-04-21T08:00:00.000-04:00||2022-04-21T11:2...,1650551340||1650563100,2022-04-21T10:29:00.000-04:00||2022-04-21T12:4...,ATL||DFW,LGA||ATL,Delta||Delta,DL||DL,Airbus A321||Airbus A321,8940||8520,762||725,coach||coach
1,1,1ad3c9a84f803cc98028ba8c67f35941,2022-04-18,2022-04-24,ATL,LGA,H3AHZNN1,PT2H22M,0,0,0,1,450.23,498.6,1,762.0,1650845400,2022-04-24T20:10:00.000-04:00,1650853920,2022-04-24T22:32:00.000-04:00,LGA,ATL,American Airlines,AA,Embraer 170,8520,762,coach
2,2,510f3a1255b9843a8eae48032b191faf,2022-04-17,2022-04-22,OAK,LAX,YH0OASMR,PT7H11M,0,0,0,0,645.02,717.0,7,1628.0,1650671280||1650688200,2022-04-22T16:48:00.000-07:00||2022-04-22T21:3...,1650678600||1650697140,2022-04-22T18:50:00.000-07:00||2022-04-22T23:5...,SEA||ONT,OAK||SEA,Alaska Airlines||Alaska Airlines,AS||AS,Embraer 175||Airbus A320,7320||8940,672||956,coach||coach
3,3,ca0fb1ee992f752bbfdcd03a8b3e8ed0,2022-04-17,2022-05-18,LGA,SFO,MAUTA5MC,PT10H22M,0,0,0,0,440.93,497.6,9,2897.0,1652904600||1652923320,2022-05-18T16:10:00.000-04:00||2022-05-18T21:2...,1652914020||1652941920,2022-05-18T18:47:00.000-04:00||2022-05-18T23:3...,ATL||SFO,LGA||ATL,Delta||Delta,DL||DL,Airbus A321||Boeing 757-300,9420||18600,762||2135,coach||coach
4,4,5f7a29384cea410317ca308d2e065059,2022-04-17,2022-05-06,SFO,BOS,E0AJZNN1,PT8H29M,1,0,0,0,506.05,567.6,3,2751.0,1651899120||1651925100,2022-05-06T21:52:00.000-07:00||2022-05-07T08:0...,1651919400||1651929660,2022-05-07T06:30:00.000-04:00||2022-05-07T09:2...,JFK||BOS,SFO||JFK,JetBlue Airways||JetBlue Airways,B6||B6,Airbus A319-321||AIRBUS INDUSTRIE A321 SHARKLETS,20280||4560,2566||185,coach||coach

In [61]:
data_from_db.tail()

,index,legId,searchDate,flightDate,startingAirport,destinationAirport,fareBasisCode,travelDuration,elapsedDays,isBasicEconomy,isRefundable,isNonStop,baseFare,totalFare,seatsRemaining,totalTravelDistance,segmentsDepartureTimeEpochSeconds,segmentsDepartureTimeRaw,segmentsArrivalTimeEpochSeconds,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsAirlineCode,segmentsEquipmentDescription,segmentsDurationInSeconds,segmentsDistance,segmentsCabinCode
4106933,4106933,782c520932c03889a92b740bfb0996b7,2022-10-05,2022-10-31,EWR,ORD,LAA4AKBS,PT4H24M,0,1,0,0,81.86,111.60,9,815.0,1667226600||1667234700,2022-10-31T10:30:00.000-04:00||2022-10-31T12:4...,1667231520||1667242440,2022-10-31T11:52:00.000-04:00||2022-10-31T13:5...,DCA||ORD,EWR||DCA,United||United,UA||UA,Embraer 170||Airbus A320,4920||7740,221||594,coach||coach
4106934,4106934,225a82ba70b0bd54549a7789f2f403ca,2022-10-05,2022-10-30,ORD,LGA,WAA3AFEN,PT2H15M,0,0,0,1,171.16,198.60,9,731.0,1667163600,2022-10-30T16:00:00.000-05:00,1667171700,2022-10-30T19:15:00.000-04:00,LGA,ORD,United,UA,Boeing 737-800,8100,731,coach
4106935,4106935,52dc84e11885f1235fe8bf95cf153ad6,2022-10-05,2022-11-05,JFK,LAX,KAUTA0MC,PT9H12M,0,0,0,0,494.89,555.61,9,2476.0,1667664000||1667681100,2022-11-05T12:00:00.000-04:00||2022-11-05T15:4...,1667673960||1667697120,2022-11-05T13:46:00.000-05:00||2022-11-05T18:1...,ORD||LAX,JFK||ORD,Delta||United,DL||UA,Canadair Regional Jet 900||Boeing 777,9960||16020,731||1745,coach||coach
4106936,4106936,d82d67aa0ff672ab83c17813a872cbe1,2022-10-05,2022-11-03,MIA,JFK,XAVSA0BC,PT2H54M,0,1,0,1,59.53,78.60,9,1095.0,1667487900,2022-11-03T11:05:00.000-04:00,1667498340,2022-11-03T13:59:00.000-04:00,JFK,MIA,Delta,DL,Boeing 737-800,10440,1095,coach
4106937,4106937,f42f0e98753134f7e69bc912ada21523,2022-10-05,2022-11-09,LAX,ORD,LAA7AWEN,PT4H4M,0,0,0,1,115.35,138.60,9,1745.0,1668018000,2022-11-09T10:20:00.000-08:00,1668032640,2022-11-09T16:24:00.000-06:00,ORD,LAX,United,UA,BOEING 787-9,14640,1745,coach

From the first and last 5 rows we can see:
- The searchDate has a timespan that goes from middle April 2022 to the beginning of October 2022 (Spring - Autumn)
- The flightDate has a timespan from end April 2022 to beginning November 2022 (also Spring - Autumn)

Search and flight dates may be influencing the price.

### Check features datatype
Info shows the number of rows and columns in the dataframe.
The datatypes are also showed.

In [62]:
data_from_db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4106938 entries, 0 to 4106937
Data columns (total 28 columns):
 #   Column                             Dtype
---  ------                             -----
 0   index                              int64
 1   legId                              object
 2   searchDate                         object
 3   flightDate                         object
 4   startingAirport                    object
 5   destinationAirport                 object
 6   fareBasisCode                      object
 7   travelDuration                     object
 8   elapsedDays                        int64
 9   isBasicEconomy                     int64
 10  isRefundable                       int64
 11  isNonStop                          int64
 12  baseFare                           float64
 13  totalFare                          float64
 14  seatsRemaining                     int64
 15  totalTravelDistance                float64
 16  segmentsDepartureTimeEpochSeconds  object
 17  segmentsDepartureTimeRaw           object
 18  segmentsArrivalTimeEpochSeconds    object
 19  segmentsArrivalTimeRaw             object
 20  segmentsArrivalAirportCode         object
 21  segmentsDepartureAirportCode       object
 22  segmentsAirlineName                object
 23  segmentsAirlineCode                object
 24  segmentsEquipmentDescription       object
 25  segmentsDurationInSeconds          object
 26  segmentsDistance                   object
 27  segmentsCabinCode                  object
dtypes: float64(3), int64(6), object(19)
memory usage: 877.3+ MB

What we can see is that most of the data is seen as categorical: some converting will be necessary before the fitting of the model.

In case we wanted to see only the datatypes of the columns we could have done: data_from_db.dtypes

### Check for duplication

In [63]:
data_from_db.nunique() # how many unique values are in each column?

index                                4106938
legId                                2221274
searchDate                               171
flightDate                               217
startingAirport                           16
destinationAirport                        16
fareBasisCode                          14994
travelDuration                          1740
elapsedDays                                3
isBasicEconomy                             2
isRefundable                               2
isNonStop                                  2
baseFare                               17564
totalFare                              30925
seatsRemaining                            11
totalTravelDistance                     3046
segmentsDepartureTimeEpochSeconds    1697154
segmentsDepartureTimeRaw             1823369
segmentsArrivalTimeEpochSeconds      1878362
segmentsArrivalTimeRaw               1977157
segmentsArrivalAirportCode              6884
segmentsDepartureAirportCode            6748
segmentsAirlineName                      130
segmentsAirlineCode                      130
segmentsEquipmentDescription            7600
segmentsDurationInSeconds             133136
segmentsDistance                       15832
segmentsCabinCode                         47
dtype: int64

### Check for null values

In [64]:
data_from_db.isnull().sum() # how many empty values have been found in the columns?

index                                     0
legId                                     0
searchDate                                0
flightDate                                0
startingAirport                           0
destinationAirport                        0
fareBasisCode                             0
travelDuration                            0
elapsedDays                               0
isBasicEconomy                            0
isRefundable                              0
isNonStop                                 0
baseFare                                  0
totalFare                                 0
seatsRemaining                            0
totalTravelDistance                  304169
segmentsDepartureTimeEpochSeconds         0
segmentsDepartureTimeRaw                  0
segmentsArrivalTimeEpochSeconds           0
segmentsArrivalTimeRaw                    0
segmentsArrivalAirportCode                0
segmentsDepartureAirportCode              0
segmentsAirlineName                       0
segmentsAirlineCode                       0
segmentsEquipmentDescription          77971
segmentsDurationInSeconds                 0
segmentsDistance                      42735
segmentsCabinCode                         0
dtype: int64

See missing values in percentage:

In [65]:
(data_from_db.isnull().sum()/(len(data_from_db)))*100

index                                0.000000
legId                                0.000000
searchDate                           0.000000
flightDate                           0.000000
startingAirport                      0.000000
destinationAirport                   0.000000
fareBasisCode                        0.000000
travelDuration                       0.000000
elapsedDays                          0.000000
isBasicEconomy                       0.000000
isRefundable                         0.000000
isNonStop                            0.000000
baseFare                             0.000000
totalFare                            0.000000
seatsRemaining                       0.000000
totalTravelDistance                  7.406223
segmentsDepartureTimeEpochSeconds    0.000000
segmentsDepartureTimeRaw             0.000000
segmentsArrivalTimeEpochSeconds      0.000000
segmentsArrivalTimeRaw               0.000000
segmentsArrivalAirportCode           0.000000
segmentsDepartureAirportCode         0.000000
segmentsAirlineName                  0.000000
segmentsAirlineCode                  0.000000
segmentsEquipmentDescription         1.898519
segmentsDurationInSeconds            0.000000
segmentsDistance                     1.040556
segmentsCabinCode                    0.000000
dtype: float64

What we can see is that 7% of the totalTravelDistance data is missing. 

We can drop the totalTravelDistance column and get the total distance using the segmentsDistance column:

If there is only one travel segment, that will be our total travel distance.

If there are two segments, we need to sum them up.

We also need to create a new column called travelDistance where these values will be stored.

### Drop really useless features

Drop features that are less probable to be correlated to the target variable (totalFare): legId, fareBasisCode.

Drop features that overcomplicate the dataframe or are duplicated/too empty: index, totalTravelDistance (will use the segments instead, total travel is too empty), segmentsDepartureTimeEpochSeconds, segmentsArrivalTimeEpochSeconds, segmentsAirlineCode, segmentsDurationInSeconds (we have travelDuration already).

Keep baseFare (maybe the obvious correlation of the less the baseFare the less the totalFare will be subverted)

In [66]:
# data_from_db = data_from_db.drop(["index", "legId", "fareBasisCode", "segmentsDistance", "segmentsDepartureTimeEpochSeconds", "segmentsArrivalTimeEpochSeconds", "segmentsAirlineCode", "segmentsDurationInSeconds"], axis=1)

### Instead of dropping columns, create a new dataset selecting the columns we are interested in

Useful columns: searchDate, flightDate, startingAirport, destinationAirport, travelDuration, elapsedDays, isBasicEconomy, isRefundable, isNonStop, baseFare, totalFare, seatsRemaining, totalTravelDistance, segmentsDepartureTimeRaw, segmentsArrivalTimeRaw, segmentsArrivalAirportCode, segmentsDepartureAirportCode, segmentsAirlineName, segmentsEquipmentDescription, segmentsCabinCode.

In [67]:
useful_features_data = data_from_db[['searchDate', 'flightDate', 'startingAirport', 'destinationAirport', 'travelDuration', 'elapsedDays', 'isBasicEconomy', 'isRefundable', 'isNonStop', 'baseFare', 'totalFare', 'seatsRemaining', 'segmentsDistance', 'segmentsDepartureTimeRaw', 'segmentsArrivalTimeRaw', 'segmentsArrivalAirportCode', 'segmentsDepartureAirportCode', 'segmentsAirlineName', 'segmentsEquipmentDescription', 'segmentsCabinCode']].copy()

In [68]:
useful_features_data.head()

,searchDate,flightDate,startingAirport,destinationAirport,travelDuration,elapsedDays,isBasicEconomy,isRefundable,isNonStop,baseFare,totalFare,seatsRemaining,segmentsDistance,segmentsDepartureTimeRaw,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsEquipmentDescription,segmentsCabinCode
0,2022-04-17,2022-04-21,LGA,DFW,PT5H45M,0,1,0,0,110.70,142.6,9,762||725,2022-04-21T08:00:00.000-04:00||2022-04-21T11:2...,2022-04-21T10:29:00.000-04:00||2022-04-21T12:4...,ATL||DFW,LGA||ATL,Delta||Delta,Airbus A321||Airbus A321,coach||coach
1,2022-04-18,2022-04-24,ATL,LGA,PT2H22M,0,0,0,1,450.23,498.6,1,762,2022-04-24T20:10:00.000-04:00,2022-04-24T22:32:00.000-04:00,LGA,ATL,American Airlines,Embraer 170,coach
2,2022-04-17,2022-04-22,OAK,LAX,PT7H11M,0,0,0,0,645.02,717.0,7,672||956,2022-04-22T16:48:00.000-07:00||2022-04-22T21:3...,2022-04-22T18:50:00.000-07:00||2022-04-22T23:5...,SEA||ONT,OAK||SEA,Alaska Airlines||Alaska Airlines,Embraer 175||Airbus A320,coach||coach
3,2022-04-17,2022-05-18,LGA,SFO,PT10H22M,0,0,0,0,440.93,497.6,9,762||2135,2022-05-18T16:10:00.000-04:00||2022-05-18T21:2...,2022-05-18T18:47:00.000-04:00||2022-05-18T23:3...,ATL||SFO,LGA||ATL,Delta||Delta,Airbus A321||Boeing 757-300,coach||coach
4,2022-04-17,2022-05-06,SFO,BOS,PT8H29M,1,0,0,0,506.05,567.6,3,2566||185,2022-05-06T21:52:00.000-07:00||2022-05-07T08:0...,2022-05-07T06:30:00.000-04:00||2022-05-07T09:2...,JFK||BOS,SFO||JFK,JetBlue Airways||JetBlue Airways,Airbus A319-321||AIRBUS INDUSTRIE A321 SHARKLETS,coach||coach

In [69]:
useful_features_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4106938 entries, 0 to 4106937
Data columns (total 20 columns):
 #   Column                        Dtype
---  ------                        -----
 0   searchDate                    object
 1   flightDate                    object
 2   startingAirport               object
 3   destinationAirport            object
 4   travelDuration                object
 5   elapsedDays                   int64
 6   isBasicEconomy                int64
 7   isRefundable                  int64
 8   isNonStop                     int64
 9   baseFare                      float64
 10  totalFare                     float64
 11  seatsRemaining                int64
 12  segmentsDistance              object
 13  segmentsDepartureTimeRaw      object
 14  segmentsArrivalTimeRaw        object
 15  segmentsArrivalAirportCode    object
 16  segmentsDepartureAirportCode  object
 17  segmentsAirlineName           object
 18  segmentsEquipmentDescription  object
 19  segmentsCabinCode             object
dtypes: float64(2), int64(5), object(13)
memory usage: 626.7+ MB

If we would want to eliminate rows with more than 2 segments, we would do this:

In [70]:
''' # Filtering rows where 'segmentsDepartureTimeRaw' column has three or more segments
mask = useful_features_data['segmentsDepartureTimeRaw'].str.count('\\|\\|').ge(2) #.ge(2):like greater than or equal to.
filtered_indices = mask[mask].index #creating a boolean mask when the rows have >2 segments. Extracts the locations where it is >2
# Dropping the filtered rows from the new DataFrame
useful_features_data.drop(filtered_indices, inplace=True) # inplace true: ensuring modification is assigned to dataframe without needing to rename it '''

" # Filtering rows where 'segmentsDepartureTimeRaw' column has three or more segments\nmask = useful_features_data['segmentsDepartureTimeRaw'].str.count('\\|\\|').ge(2) #.ge(2):like greater than or equal to.\nfiltered_indices = mask[mask].index #creating a boolean mask when the rows have >2 segments. Extracts the locations where it is >2\n# Dropping the filtered rows from the new DataFrame\nuseful_features_data.drop(filtered_indices, inplace=True) # inplace true: ensuring modification is assigned to dataframe without needing to rename it "

In [71]:
''' # Check if it is working/Check how many segments there are with more than two segments
# Counting the number of rows with three or more segments
count = useful_features_data['segmentsDepartureTimeRaw'].str.count('\\|\\|').ge(2).sum() #.ge(2):like greater than or equal to.
# Displaying the count
print(f"Number of rows with three or more segments: {count}")
# it was around 388621 for departure raw '''

' # Check if it is working/Check how many segments there are with more than two segments\n# Counting the number of rows with three or more segments\ncount = useful_features_data[\'segmentsDepartureTimeRaw\'].str.count(\'\\|\\|\').ge(2).sum() #.ge(2):like greater than or equal to.\n# Displaying the count\nprint(f"Number of rows with three or more segments: {count}")\n# it was around 388621 for departure raw '

### Check how many segments are there

In [72]:
# Check maximum numbers of segments by checking how many || there are, take one modified column from above as example
how_many_segments = useful_features_data["segmentsArrivalTimeRaw"].apply(lambda s : len(s.split("||")))

In [73]:
how_many_segments.max()

5

We have up to 5 segments

### Split the segment columns into the respective segments and create new columns for each segment

segmentsDistance, segmentsDepartureTimeRaw, segmentsArrivalTimeRaw, segmentsArrivalAirportCode, segmentsDepartureAirportCode, segmentsAirlineName, segmentsEquipmentDescription, segmentsCabinCode

In [74]:
useful_features_data['segmentsDistance']

0           762||725
1                762
2           672||956
3          762||2135
4          2566||185
             ...
4106933     221||594
4106934          731
4106935    731||1745
4106936         1095
4106937         1745
Name: segmentsDistance, Length: 4106938, dtype: object

In [75]:
useful_features_data['segmentsDistance'].iloc[:100].str.split('\|\|')

<>:1: SyntaxWarning: invalid escape sequence '\|'
<>:1: SyntaxWarning: invalid escape sequence '\|'
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\1776367060.py:1: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['segmentsDistance'].iloc[:100].str.split('\|\|')

0          [762, 725]
1               [762]
2          [672, 956]
3         [762, 2135]
4         [2566, 185]
           ...
95        [339, 1943]
96    [185, 406, 923]
97              [720]
98              [339]
99              [351]
Name: segmentsDistance, Length: 100, dtype: object

In [76]:
useful_features_data['1segDistance'] = useful_features_data['segmentsDistance'].str.split('\|\|').apply(lambda d: d[0] if d is not None and len(d) > 0 else None)
useful_features_data['2segDistance'] = useful_features_data['segmentsDistance'].str.split('\|\|').apply(lambda d: d[1] if d is not None and len(d) > 1 else None)
useful_features_data['3segDistance'] = useful_features_data['segmentsDistance'].str.split('\|\|').apply(lambda d: d[2] if d is not None and len(d) > 2 else None)
useful_features_data['4segDistance'] = useful_features_data['segmentsDistance'].str.split('\|\|').apply(lambda d: d[3] if d is not None and len(d) > 3 else None)
useful_features_data['5segDistance'] = useful_features_data['segmentsDistance'].str.split('\|\|').apply(lambda d: d[4] if d is not None and len(d) > 4 else None)

<>:1: SyntaxWarning: invalid escape sequence '\|'
<>:2: SyntaxWarning: invalid escape sequence '\|'
<>:3: SyntaxWarning: invalid escape sequence '\|'
<>:4: SyntaxWarning: invalid escape sequence '\|'
<>:5: SyntaxWarning: invalid escape sequence '\|'
<>:1: SyntaxWarning: invalid escape sequence '\|'
<>:2: SyntaxWarning: invalid escape sequence '\|'
<>:3: SyntaxWarning: invalid escape sequence '\|'
<>:4: SyntaxWarning: invalid escape sequence '\|'
<>:5: SyntaxWarning: invalid escape sequence '\|'
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\498839281.py:1: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['1segDistance'] = useful_features_data['segmentsDistance'].str.split('\|\|').apply(lambda d: d[0] if d is not None and len(d) > 0 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\498839281.py:2: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['2segDistance'] = useful_features_data['segmentsDistance'].str.split('\|\|').apply(lambda d: d[1] if d is not None and len(d) > 1 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\498839281.py:3: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['3segDistance'] = useful_features_data['segmentsDistance'].str.split('\|\|').apply(lambda d: d[2] if d is not None and len(d) > 2 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\498839281.py:4: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['4segDistance'] = useful_features_data['segmentsDistance'].str.split('\|\|').apply(lambda d: d[3] if d is not None and len(d) > 3 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\498839281.py:5: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['5segDistance'] = useful_features_data['segmentsDistance'].str.split('\|\|').apply(lambda d: d[4] if d is not None and len(d) > 4 else None)

In [77]:
useful_features_data['1depTime'] = useful_features_data['segmentsDepartureTimeRaw'].str.split('\|\|').apply(lambda d: d[0] if d is not None and len(d) > 0 else None)
useful_features_data['2depTime'] = useful_features_data['segmentsDepartureTimeRaw'].str.split('\|\|').apply(lambda d: d[1] if d is not None and len(d) > 1 else None)
useful_features_data['3depTime'] = useful_features_data['segmentsDepartureTimeRaw'].str.split('\|\|').apply(lambda d: d[2] if d is not None and len(d) > 2 else None)
useful_features_data['4depTime'] = useful_features_data['segmentsDepartureTimeRaw'].str.split('\|\|').apply(lambda d: d[3] if d is not None and len(d) > 3 else None)
useful_features_data['5depTime'] = useful_features_data['segmentsDepartureTimeRaw'].str.split('\|\|').apply(lambda d: d[4] if d is not None and len(d) > 4 else None)

<>:1: SyntaxWarning: invalid escape sequence '\|'
<>:2: SyntaxWarning: invalid escape sequence '\|'
<>:3: SyntaxWarning: invalid escape sequence '\|'
<>:4: SyntaxWarning: invalid escape sequence '\|'
<>:5: SyntaxWarning: invalid escape sequence '\|'
<>:1: SyntaxWarning: invalid escape sequence '\|'
<>:2: SyntaxWarning: invalid escape sequence '\|'
<>:3: SyntaxWarning: invalid escape sequence '\|'
<>:4: SyntaxWarning: invalid escape sequence '\|'
<>:5: SyntaxWarning: invalid escape sequence '\|'
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\1860736742.py:1: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['1depTime'] = useful_features_data['segmentsDepartureTimeRaw'].str.split('\|\|').apply(lambda d: d[0] if d is not None and len(d) > 0 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\1860736742.py:2: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['2depTime'] = useful_features_data['segmentsDepartureTimeRaw'].str.split('\|\|').apply(lambda d: d[1] if d is not None and len(d) > 1 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\1860736742.py:3: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['3depTime'] = useful_features_data['segmentsDepartureTimeRaw'].str.split('\|\|').apply(lambda d: d[2] if d is not None and len(d) > 2 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\1860736742.py:4: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['4depTime'] = useful_features_data['segmentsDepartureTimeRaw'].str.split('\|\|').apply(lambda d: d[3] if d is not None and len(d) > 3 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\1860736742.py:5: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['5depTime'] = useful_features_data['segmentsDepartureTimeRaw'].str.split('\|\|').apply(lambda d: d[4] if d is not None and len(d) > 4 else None)

In [78]:
useful_features_data['1arrTime'] = useful_features_data['segmentsArrivalTimeRaw'].str.split('\|\|').apply(lambda d: d[0] if d is not None and len(d) > 0 else None)
useful_features_data['2arrTime'] = useful_features_data['segmentsArrivalTimeRaw'].str.split('\|\|').apply(lambda d: d[1] if d is not None and len(d) > 1 else None)
useful_features_data['3arrTime'] = useful_features_data['segmentsArrivalTimeRaw'].str.split('\|\|').apply(lambda d: d[2] if d is not None and len(d) > 2 else None)
useful_features_data['4arrTime'] = useful_features_data['segmentsArrivalTimeRaw'].str.split('\|\|').apply(lambda d: d[3] if d is not None and len(d) > 3 else None)
useful_features_data['5arrTime'] = useful_features_data['segmentsArrivalTimeRaw'].str.split('\|\|').apply(lambda d: d[4] if d is not None and len(d) > 4 else None)

<>:1: SyntaxWarning: invalid escape sequence '\|'
<>:2: SyntaxWarning: invalid escape sequence '\|'
<>:3: SyntaxWarning: invalid escape sequence '\|'
<>:4: SyntaxWarning: invalid escape sequence '\|'
<>:5: SyntaxWarning: invalid escape sequence '\|'
<>:1: SyntaxWarning: invalid escape sequence '\|'
<>:2: SyntaxWarning: invalid escape sequence '\|'
<>:3: SyntaxWarning: invalid escape sequence '\|'
<>:4: SyntaxWarning: invalid escape sequence '\|'
<>:5: SyntaxWarning: invalid escape sequence '\|'
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\274079980.py:1: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['1arrTime'] = useful_features_data['segmentsArrivalTimeRaw'].str.split('\|\|').apply(lambda d: d[0] if d is not None and len(d) > 0 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\274079980.py:2: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['2arrTime'] = useful_features_data['segmentsArrivalTimeRaw'].str.split('\|\|').apply(lambda d: d[1] if d is not None and len(d) > 1 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\274079980.py:3: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['3arrTime'] = useful_features_data['segmentsArrivalTimeRaw'].str.split('\|\|').apply(lambda d: d[2] if d is not None and len(d) > 2 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\274079980.py:4: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['4arrTime'] = useful_features_data['segmentsArrivalTimeRaw'].str.split('\|\|').apply(lambda d: d[3] if d is not None and len(d) > 3 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\274079980.py:5: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['5arrTime'] = useful_features_data['segmentsArrivalTimeRaw'].str.split('\|\|').apply(lambda d: d[4] if d is not None and len(d) > 4 else None)

In [79]:
useful_features_data['1arrAirport'] = useful_features_data['segmentsArrivalAirportCode'].str.split('\|\|').apply(lambda d: d[0] if d is not None and len(d) > 0 else None)
useful_features_data['2arrAirport'] = useful_features_data['segmentsArrivalAirportCode'].str.split('\|\|').apply(lambda d: d[1] if d is not None and len(d) > 1 else None)
useful_features_data['3arrAirport'] = useful_features_data['segmentsArrivalAirportCode'].str.split('\|\|').apply(lambda d: d[2] if d is not None and len(d) > 2 else None)
useful_features_data['4arrAirport'] = useful_features_data['segmentsArrivalAirportCode'].str.split('\|\|').apply(lambda d: d[3] if d is not None and len(d) > 3 else None)
useful_features_data['5arrAirport'] = useful_features_data['segmentsArrivalAirportCode'].str.split('\|\|').apply(lambda d: d[4] if d is not None and len(d) > 4 else None)

<>:1: SyntaxWarning: invalid escape sequence '\|'
<>:2: SyntaxWarning: invalid escape sequence '\|'
<>:3: SyntaxWarning: invalid escape sequence '\|'
<>:4: SyntaxWarning: invalid escape sequence '\|'
<>:5: SyntaxWarning: invalid escape sequence '\|'
<>:1: SyntaxWarning: invalid escape sequence '\|'
<>:2: SyntaxWarning: invalid escape sequence '\|'
<>:3: SyntaxWarning: invalid escape sequence '\|'
<>:4: SyntaxWarning: invalid escape sequence '\|'
<>:5: SyntaxWarning: invalid escape sequence '\|'
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\511713796.py:1: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['1arrAirport'] = useful_features_data['segmentsArrivalAirportCode'].str.split('\|\|').apply(lambda d: d[0] if d is not None and len(d) > 0 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\511713796.py:2: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['2arrAirport'] = useful_features_data['segmentsArrivalAirportCode'].str.split('\|\|').apply(lambda d: d[1] if d is not None and len(d) > 1 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\511713796.py:3: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['3arrAirport'] = useful_features_data['segmentsArrivalAirportCode'].str.split('\|\|').apply(lambda d: d[2] if d is not None and len(d) > 2 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\511713796.py:4: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['4arrAirport'] = useful_features_data['segmentsArrivalAirportCode'].str.split('\|\|').apply(lambda d: d[3] if d is not None and len(d) > 3 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\511713796.py:5: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['5arrAirport'] = useful_features_data['segmentsArrivalAirportCode'].str.split('\|\|').apply(lambda d: d[4] if d is not None and len(d) > 4 else None)

In [80]:
useful_features_data['1depAirport'] = useful_features_data['segmentsDepartureAirportCode'].str.split('\|\|').apply(lambda d: d[0] if d is not None and len(d) > 0 else None)
useful_features_data['2depAirport'] = useful_features_data['segmentsDepartureAirportCode'].str.split('\|\|').apply(lambda d: d[1] if d is not None and len(d) > 1 else None)
useful_features_data['3depAirport'] = useful_features_data['segmentsDepartureAirportCode'].str.split('\|\|').apply(lambda d: d[2] if d is not None and len(d) > 2 else None)
useful_features_data['4depAirport'] = useful_features_data['segmentsDepartureAirportCode'].str.split('\|\|').apply(lambda d: d[3] if d is not None and len(d) > 3 else None)
useful_features_data['5depAirport'] = useful_features_data['segmentsDepartureAirportCode'].str.split('\|\|').apply(lambda d: d[4] if d is not None and len(d) > 4 else None)

<>:1: SyntaxWarning: invalid escape sequence '\|'
<>:2: SyntaxWarning: invalid escape sequence '\|'
<>:3: SyntaxWarning: invalid escape sequence '\|'
<>:4: SyntaxWarning: invalid escape sequence '\|'
<>:5: SyntaxWarning: invalid escape sequence '\|'
<>:1: SyntaxWarning: invalid escape sequence '\|'
<>:2: SyntaxWarning: invalid escape sequence '\|'
<>:3: SyntaxWarning: invalid escape sequence '\|'
<>:4: SyntaxWarning: invalid escape sequence '\|'
<>:5: SyntaxWarning: invalid escape sequence '\|'
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\224683536.py:1: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['1depAirport'] = useful_features_data['segmentsDepartureAirportCode'].str.split('\|\|').apply(lambda d: d[0] if d is not None and len(d) > 0 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\224683536.py:2: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['2depAirport'] = useful_features_data['segmentsDepartureAirportCode'].str.split('\|\|').apply(lambda d: d[1] if d is not None and len(d) > 1 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\224683536.py:3: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['3depAirport'] = useful_features_data['segmentsDepartureAirportCode'].str.split('\|\|').apply(lambda d: d[2] if d is not None and len(d) > 2 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\224683536.py:4: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['4depAirport'] = useful_features_data['segmentsDepartureAirportCode'].str.split('\|\|').apply(lambda d: d[3] if d is not None and len(d) > 3 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\224683536.py:5: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['5depAirport'] = useful_features_data['segmentsDepartureAirportCode'].str.split('\|\|').apply(lambda d: d[4] if d is not None and len(d) > 4 else None)

In [81]:
useful_features_data['1airline'] = useful_features_data['segmentsAirlineName'].str.split('\|\|').apply(lambda d: d[0] if d is not None and len(d) > 0 else None)
useful_features_data['2airline'] = useful_features_data['segmentsAirlineName'].str.split('\|\|').apply(lambda d: d[1] if d is not None and len(d) > 1 else None)
useful_features_data['3airline'] = useful_features_data['segmentsAirlineName'].str.split('\|\|').apply(lambda d: d[2] if d is not None and len(d) > 2 else None)
useful_features_data['4airline'] = useful_features_data['segmentsAirlineName'].str.split('\|\|').apply(lambda d: d[3] if d is not None and len(d) > 3 else None)
useful_features_data['5airline'] = useful_features_data['segmentsAirlineName'].str.split('\|\|').apply(lambda d: d[4] if d is not None and len(d) > 4 else None)

<>:1: SyntaxWarning: invalid escape sequence '\|'
<>:2: SyntaxWarning: invalid escape sequence '\|'
<>:3: SyntaxWarning: invalid escape sequence '\|'
<>:4: SyntaxWarning: invalid escape sequence '\|'
<>:5: SyntaxWarning: invalid escape sequence '\|'
<>:1: SyntaxWarning: invalid escape sequence '\|'
<>:2: SyntaxWarning: invalid escape sequence '\|'
<>:3: SyntaxWarning: invalid escape sequence '\|'
<>:4: SyntaxWarning: invalid escape sequence '\|'
<>:5: SyntaxWarning: invalid escape sequence '\|'
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\2193634677.py:1: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['1airline'] = useful_features_data['segmentsAirlineName'].str.split('\|\|').apply(lambda d: d[0] if d is not None and len(d) > 0 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\2193634677.py:2: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['2airline'] = useful_features_data['segmentsAirlineName'].str.split('\|\|').apply(lambda d: d[1] if d is not None and len(d) > 1 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\2193634677.py:3: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['3airline'] = useful_features_data['segmentsAirlineName'].str.split('\|\|').apply(lambda d: d[2] if d is not None and len(d) > 2 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\2193634677.py:4: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['4airline'] = useful_features_data['segmentsAirlineName'].str.split('\|\|').apply(lambda d: d[3] if d is not None and len(d) > 3 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\2193634677.py:5: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['5airline'] = useful_features_data['segmentsAirlineName'].str.split('\|\|').apply(lambda d: d[4] if d is not None and len(d) > 4 else None)

In [82]:
useful_features_data['1equipment'] = useful_features_data['segmentsEquipmentDescription'].str.split('\|\|').apply(lambda d: d[0] if d is not None and len(d) > 0 else None)
useful_features_data['2equipment'] = useful_features_data['segmentsEquipmentDescription'].str.split('\|\|').apply(lambda d: d[1] if d is not None and len(d) > 1 else None)
useful_features_data['3equipment'] = useful_features_data['segmentsEquipmentDescription'].str.split('\|\|').apply(lambda d: d[2] if d is not None and len(d) > 2 else None)
useful_features_data['4equipment'] = useful_features_data['segmentsEquipmentDescription'].str.split('\|\|').apply(lambda d: d[3] if d is not None and len(d) > 3 else None)
useful_features_data['5equipment'] = useful_features_data['segmentsEquipmentDescription'].str.split('\|\|').apply(lambda d: d[4] if d is not None and len(d) > 4 else None)

<>:1: SyntaxWarning: invalid escape sequence '\|'
<>:2: SyntaxWarning: invalid escape sequence '\|'
<>:3: SyntaxWarning: invalid escape sequence '\|'
<>:4: SyntaxWarning: invalid escape sequence '\|'
<>:5: SyntaxWarning: invalid escape sequence '\|'
<>:1: SyntaxWarning: invalid escape sequence '\|'
<>:2: SyntaxWarning: invalid escape sequence '\|'
<>:3: SyntaxWarning: invalid escape sequence '\|'
<>:4: SyntaxWarning: invalid escape sequence '\|'
<>:5: SyntaxWarning: invalid escape sequence '\|'
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\834389069.py:1: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['1equipment'] = useful_features_data['segmentsEquipmentDescription'].str.split('\|\|').apply(lambda d: d[0] if d is not None and len(d) > 0 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\834389069.py:2: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['2equipment'] = useful_features_data['segmentsEquipmentDescription'].str.split('\|\|').apply(lambda d: d[1] if d is not None and len(d) > 1 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\834389069.py:3: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['3equipment'] = useful_features_data['segmentsEquipmentDescription'].str.split('\|\|').apply(lambda d: d[2] if d is not None and len(d) > 2 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\834389069.py:4: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['4equipment'] = useful_features_data['segmentsEquipmentDescription'].str.split('\|\|').apply(lambda d: d[3] if d is not None and len(d) > 3 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\834389069.py:5: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['5equipment'] = useful_features_data['segmentsEquipmentDescription'].str.split('\|\|').apply(lambda d: d[4] if d is not None and len(d) > 4 else None)

In [83]:
useful_features_data['1cabin'] = useful_features_data['segmentsCabinCode'].str.split('\|\|').apply(lambda d: d[0] if d is not None and len(d) > 0 else None)
useful_features_data['2cabin'] = useful_features_data['segmentsCabinCode'].str.split('\|\|').apply(lambda d: d[1] if d is not None and len(d) > 1 else None)
useful_features_data['3cabin'] = useful_features_data['segmentsCabinCode'].str.split('\|\|').apply(lambda d: d[2] if d is not None and len(d) > 2 else None)
useful_features_data['4cabin'] = useful_features_data['segmentsCabinCode'].str.split('\|\|').apply(lambda d: d[3] if d is not None and len(d) > 3 else None)
useful_features_data['5cabin'] = useful_features_data['segmentsCabinCode'].str.split('\|\|').apply(lambda d: d[4] if d is not None and len(d) > 4 else None)

<>:1: SyntaxWarning: invalid escape sequence '\|'
<>:2: SyntaxWarning: invalid escape sequence '\|'
<>:3: SyntaxWarning: invalid escape sequence '\|'
<>:4: SyntaxWarning: invalid escape sequence '\|'
<>:5: SyntaxWarning: invalid escape sequence '\|'
<>:1: SyntaxWarning: invalid escape sequence '\|'
<>:2: SyntaxWarning: invalid escape sequence '\|'
<>:3: SyntaxWarning: invalid escape sequence '\|'
<>:4: SyntaxWarning: invalid escape sequence '\|'
<>:5: SyntaxWarning: invalid escape sequence '\|'
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\396150046.py:1: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['1cabin'] = useful_features_data['segmentsCabinCode'].str.split('\|\|').apply(lambda d: d[0] if d is not None and len(d) > 0 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\396150046.py:2: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['2cabin'] = useful_features_data['segmentsCabinCode'].str.split('\|\|').apply(lambda d: d[1] if d is not None and len(d) > 1 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\396150046.py:3: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['3cabin'] = useful_features_data['segmentsCabinCode'].str.split('\|\|').apply(lambda d: d[2] if d is not None and len(d) > 2 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\396150046.py:4: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['4cabin'] = useful_features_data['segmentsCabinCode'].str.split('\|\|').apply(lambda d: d[3] if d is not None and len(d) > 3 else None)
C:\Users\Anna\AppData\Local\Temp\ipykernel_18792\396150046.py:5: SyntaxWarning: invalid escape sequence '\|'
  useful_features_data['5cabin'] = useful_features_data['segmentsCabinCode'].str.split('\|\|').apply(lambda d: d[4] if d is not None and len(d) > 4 else None)

In [84]:
useful_features_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4106938 entries, 0 to 4106937
Data columns (total 60 columns):
 #   Column                        Dtype
---  ------                        -----
 0   searchDate                    object
 1   flightDate                    object
 2   startingAirport               object
 3   destinationAirport            object
 4   travelDuration                object
 5   elapsedDays                   int64
 6   isBasicEconomy                int64
 7   isRefundable                  int64
 8   isNonStop                     int64
 9   baseFare                      float64
 10  totalFare                     float64
 11  seatsRemaining                int64
 12  segmentsDistance              object
 13  segmentsDepartureTimeRaw      object
 14  segmentsArrivalTimeRaw        object
 15  segmentsArrivalAirportCode    object
 16  segmentsDepartureAirportCode  object
 17  segmentsAirlineName           object
 18  segmentsEquipmentDescription  object
 19  segmentsCabinCode             object
 20  1segDistance                  object
 21  2segDistance                  object
 22  3segDistance                  object
 23  4segDistance                  object
 24  5segDistance                  object
 25  1depTime                      object
 26  2depTime                      object
 27  3depTime                      object
 28  4depTime                      object
 29  5depTime                      object
 30  1arrTime                      object
 31  2arrTime                      object
 32  3arrTime                      object
 33  4arrTime                      object
 34  5arrTime                      object
 35  1arrAirport                   object
 36  2arrAirport                   object
 37  3arrAirport                   object
 38  4arrAirport                   object
 39  5arrAirport                   object
 40  1depAirport                   object
 41  2depAirport                   object
 42  3depAirport                   object
 43  4depAirport                   object
 44  5depAirport                   object
 45  1airline                      object
 46  2airline                      object
 47  3airline                      object
 48  4airline                      object
 49  5airline                      object
 50  1equipment                    object
 51  2equipment                    object
 52  3equipment                    object
 53  4equipment                    object
 54  5equipment                    object
 55  1cabin                        object
 56  2cabin                        object
 57  3cabin                        object
 58  4cabin                        object
 59  5cabin                        object
dtypes: float64(2), int64(5), object(53)
memory usage: 1.8+ GB

In [85]:
useful_features_data.head()

,searchDate,flightDate,startingAirport,destinationAirport,travelDuration,elapsedDays,isBasicEconomy,isRefundable,isNonStop,baseFare,totalFare,seatsRemaining,segmentsDistance,segmentsDepartureTimeRaw,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsEquipmentDescription,segmentsCabinCode,1segDistance,2segDistance,3segDistance,4segDistance,5segDistance,1depTime,2depTime,3depTime,4depTime,5depTime,1arrTime,2arrTime,3arrTime,4arrTime,5arrTime,1arrAirport,2arrAirport,3arrAirport,4arrAirport,5arrAirport,1depAirport,2depAirport,3depAirport,4depAirport,5depAirport,1airline,2airline,3airline,4airline,5airline,1equipment,2equipment,3equipment,4equipment,5equipment,1cabin,2cabin,3cabin,4cabin,5cabin
0,2022-04-17,2022-04-21,LGA,DFW,PT5H45M,0,1,0,0,110.70,142.6,9,762||725,2022-04-21T08:00:00.000-04:00||2022-04-21T11:2...,2022-04-21T10:29:00.000-04:00||2022-04-21T12:4...,ATL||DFW,LGA||ATL,Delta||Delta,Airbus A321||Airbus A321,coach||coach,762,725,None,None,None,2022-04-21T08:00:00.000-04:00,2022-04-21T11:23:00.000-04:00,None,None,None,2022-04-21T10:29:00.000-04:00,2022-04-21T12:45:00.000-05:00,None,None,None,ATL,DFW,None,None,None,LGA,ATL,None,None,None,Delta,Delta,None,None,None,Airbus A321,Airbus A321,None,None,None,coach,coach,None,None,None
1,2022-04-18,2022-04-24,ATL,LGA,PT2H22M,0,0,0,1,450.23,498.6,1,762,2022-04-24T20:10:00.000-04:00,2022-04-24T22:32:00.000-04:00,LGA,ATL,American Airlines,Embraer 170,coach,762,None,None,None,None,2022-04-24T20:10:00.000-04:00,None,None,None,None,2022-04-24T22:32:00.000-04:00,None,None,None,None,LGA,None,None,None,None,ATL,None,None,None,None,American Airlines,None,None,None,None,Embraer 170,None,None,None,None,coach,None,None,None,None
2,2022-04-17,2022-04-22,OAK,LAX,PT7H11M,0,0,0,0,645.02,717.0,7,672||956,2022-04-22T16:48:00.000-07:00||2022-04-22T21:3...,2022-04-22T18:50:00.000-07:00||2022-04-22T23:5...,SEA||ONT,OAK||SEA,Alaska Airlines||Alaska Airlines,Embraer 175||Airbus A320,coach||coach,672,956,None,None,None,2022-04-22T16:48:00.000-07:00,2022-04-22T21:30:00.000-07:00,None,None,None,2022-04-22T18:50:00.000-07:00,2022-04-22T23:59:00.000-07:00,None,None,None,SEA,ONT,None,None,None,OAK,SEA,None,None,None,Alaska Airlines,Alaska Airlines,None,None,None,Embraer 175,Airbus A320,None,None,None,coach,coach,None,None,None
3,2022-04-17,2022-05-18,LGA,SFO,PT10H22M,0,0,0,0,440.93,497.6,9,762||2135,2022-05-18T16:10:00.000-04:00||2022-05-18T21:2...,2022-05-18T18:47:00.000-04:00||2022-05-18T23:3...,ATL||SFO,LGA||ATL,Delta||Delta,Airbus A321||Boeing 757-300,coach||coach,762,2135,None,None,None,2022-05-18T16:10:00.000-04:00,2022-05-18T21:22:00.000-04:00,None,None,None,2022-05-18T18:47:00.000-04:00,2022-05-18T23:32:00.000-07:00,None,None,None,ATL,SFO,None,None,None,LGA,ATL,None,None,None,Delta,Delta,None,None,None,Airbus A321,Boeing 757-300,None,None,None,coach,coach,None,None,None
4,2022-04-17,2022-05-06,SFO,BOS,PT8H29M,1,0,0,0,506.05,567.6,3,2566||185,2022-05-06T21:52:00.000-07:00||2022-05-07T08:0...,2022-05-07T06:30:00.000-04:00||2022-05-07T09:2...,JFK||BOS,SFO||JFK,JetBlue Airways||JetBlue Airways,Airbus A319-321||AIRBUS INDUSTRIE A321 SHARKLETS,coach||coach,2566,185,None,None,None,2022-05-06T21:52:00.000-07:00,2022-05-07T08:05:00.000-04:00,None,None,None,2022-05-07T06:30:00.000-04:00,2022-05-07T09:21:00.000-04:00,None,None,None,JFK,BOS,None,None,None,SFO,JFK,None,None,None,JetBlue Airways,JetBlue Airways,None,None,None,Airbus A319-321,AIRBUS INDUSTRIE A321 SHARKLETS,None,None,None,coach,coach,None,None,None

Separate 1depTime date and time (we already have the date, we just want to see the time). Do the same for 2depTime, 1arrTime and 2arrTime.

In [103]:
# Extract time component from 1depTime column
useful_features_data['1depTimeOnly'] = useful_features_data['1depTime'].str.split('T').str[1].str.split("-").str[0]
# Displaying the DataFrame with the new column
print(useful_features_data[['1depTime', '1depTimeOnly']].head())

                        1depTime  1depTimeOnly
0  2022-04-21T08:00:00.000-04:00  08:00:00.000
1  2022-04-24T20:10:00.000-04:00  20:10:00.000
2  2022-04-22T16:48:00.000-07:00  16:48:00.000
3  2022-05-18T16:10:00.000-04:00  16:10:00.000
4  2022-05-06T21:52:00.000-07:00  21:52:00.000

In [105]:
# Extract time component from 1depTime column
useful_features_data['2depTimeOnly'] = useful_features_data['2depTime'].str.split('T').str[1].str.split("-").str[0]
# Displaying the DataFrame with the new column
print(useful_features_data[['2depTime', '2depTimeOnly']].head())

                        2depTime  2depTimeOnly
0  2022-04-21T11:23:00.000-04:00  11:23:00.000
1                           None          None
2  2022-04-22T21:30:00.000-07:00  21:30:00.000
3  2022-05-18T21:22:00.000-04:00  21:22:00.000
4  2022-05-07T08:05:00.000-04:00  08:05:00.000

In [107]:
# Extract time component from 1depTime column
useful_features_data['3depTimeOnly'] = useful_features_data['3depTime'].str.split('T').str[1].str.split("-").str[0]
# Displaying the DataFrame with the new column
print(useful_features_data[['3depTime', '3depTimeOnly']].head())

  3depTime 3depTimeOnly
0     None         None
1     None         None
2     None         None
3     None         None
4     None         None

In [109]:
# Extract time component from 1depTime column
useful_features_data['4depTimeOnly'] = useful_features_data['4depTime'].str.split('T').str[1].str.split("-").str[0]
# Displaying the DataFrame with the new column
print(useful_features_data[['4depTime', '4depTimeOnly']].head())

  4depTime 4depTimeOnly
0     None         None
1     None         None
2     None         None
3     None         None
4     None         None

In [110]:
# Extract time component from 1depTime column
useful_features_data['5depTimeOnly'] = useful_features_data['5depTime'].str.split('T').str[1].str.split("-").str[0]
# Displaying the DataFrame with the new column
print(useful_features_data[['5depTime', '5depTimeOnly']].head())

  5depTime 5depTimeOnly
0     None         None
1     None         None
2     None         None
3     None         None
4     None         None

In [111]:
# Extract time component from 1depTime column
useful_features_data['1arrTimeOnly'] = useful_features_data['1arrTime'].str.split('T').str[1].str.split("-").str[0]
# Displaying the DataFrame with the new column
print(useful_features_data[['1arrTime', '1arrTimeOnly']].head())

                        1arrTime  1arrTimeOnly
0  2022-04-21T10:29:00.000-04:00  10:29:00.000
1  2022-04-24T22:32:00.000-04:00  22:32:00.000
2  2022-04-22T18:50:00.000-07:00  18:50:00.000
3  2022-05-18T18:47:00.000-04:00  18:47:00.000
4  2022-05-07T06:30:00.000-04:00  06:30:00.000

In [113]:
# Extract time component from 1depTime column
useful_features_data['2arrTimeOnly'] = useful_features_data['2arrTime'].str.split('T').str[1].str.split("-").str[0]
# Displaying the DataFrame with the new column
print(useful_features_data[['2arrTime', '2arrTimeOnly']].head())

                        2arrTime  2arrTimeOnly
0  2022-04-21T12:45:00.000-05:00  12:45:00.000
1                           None          None
2  2022-04-22T23:59:00.000-07:00  23:59:00.000
3  2022-05-18T23:32:00.000-07:00  23:32:00.000
4  2022-05-07T09:21:00.000-04:00  09:21:00.000

In [114]:
# Extract time component from 1depTime column
useful_features_data['3arrTimeOnly'] = useful_features_data['3arrTime'].str.split('T').str[1].str.split("-").str[0]
# Displaying the DataFrame with the new column
print(useful_features_data[['3arrTime', '3arrTimeOnly']].head())

  3arrTime 3arrTimeOnly
0     None         None
1     None         None
2     None         None
3     None         None
4     None         None

In [115]:
# Extract time component from 1depTime column
useful_features_data['4arrTimeOnly'] = useful_features_data['4arrTime'].str.split('T').str[1].str.split("-").str[0]
# Displaying the DataFrame with the new column
print(useful_features_data[['4arrTime', '4arrTimeOnly']].head())

  4arrTime 4arrTimeOnly
0     None         None
1     None         None
2     None         None
3     None         None
4     None         None

In [116]:
# Extract time component from 1depTime column
useful_features_data['5arrTimeOnly'] = useful_features_data['5arrTime'].str.split('T').str[1].str.split("-").str[0]
# Displaying the DataFrame with the new column
print(useful_features_data[['5arrTime', '5arrTimeOnly']].head())

  5arrTime 5arrTimeOnly
0     None         None
1     None         None
2     None         None
3     None         None
4     None         None

In [117]:
useful_features_data.head()

,searchDate,flightDate,startingAirport,destinationAirport,travelDuration,elapsedDays,isBasicEconomy,isRefundable,isNonStop,baseFare,totalFare,seatsRemaining,segmentsDistance,segmentsDepartureTimeRaw,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsEquipmentDescription,segmentsCabinCode,1segDistance,2segDistance,3segDistance,4segDistance,5segDistance,1depTime,2depTime,3depTime,4depTime,5depTime,1arrTime,2arrTime,3arrTime,4arrTime,5arrTime,1arrAirport,2arrAirport,3arrAirport,4arrAirport,5arrAirport,1depAirport,2depAirport,3depAirport,4depAirport,5depAirport,1airline,2airline,3airline,4airline,5airline,1equipment,2equipment,3equipment,4equipment,5equipment,1cabin,2cabin,3cabin,4cabin,5cabin,1depTimeOnly,2depTimeOnly,3depTimeOnly,4depTimeOnly,5depTimeOnly,1arrTimeOnly,2arrTimeOnly,3arrTimeOnly,4arrTimeOnly,5arrTimeOnly
0,2022-04-17,2022-04-21,LGA,DFW,PT5H45M,0,1,0,0,110.70,142.6,9,762||725,2022-04-21T08:00:00.000-04:00||2022-04-21T11:2...,2022-04-21T10:29:00.000-04:00||2022-04-21T12:4...,ATL||DFW,LGA||ATL,Delta||Delta,Airbus A321||Airbus A321,coach||coach,762,725,None,None,None,2022-04-21T08:00:00.000-04:00,2022-04-21T11:23:00.000-04:00,None,None,None,2022-04-21T10:29:00.000-04:00,2022-04-21T12:45:00.000-05:00,None,None,None,ATL,DFW,None,None,None,LGA,ATL,None,None,None,Delta,Delta,None,None,None,Airbus A321,Airbus A321,None,None,None,coach,coach,None,None,None,08:00:00.000,11:23:00.000,None,None,None,10:29:00.000,12:45:00.000,None,None,None
1,2022-04-18,2022-04-24,ATL,LGA,PT2H22M,0,0,0,1,450.23,498.6,1,762,2022-04-24T20:10:00.000-04:00,2022-04-24T22:32:00.000-04:00,LGA,ATL,American Airlines,Embraer 170,coach,762,None,None,None,None,2022-04-24T20:10:00.000-04:00,None,None,None,None,2022-04-24T22:32:00.000-04:00,None,None,None,None,LGA,None,None,None,None,ATL,None,None,None,None,American Airlines,None,None,None,None,Embraer 170,None,None,None,None,coach,None,None,None,None,20:10:00.000,None,None,None,None,22:32:00.000,None,None,None,None
2,2022-04-17,2022-04-22,OAK,LAX,PT7H11M,0,0,0,0,645.02,717.0,7,672||956,2022-04-22T16:48:00.000-07:00||2022-04-22T21:3...,2022-04-22T18:50:00.000-07:00||2022-04-22T23:5...,SEA||ONT,OAK||SEA,Alaska Airlines||Alaska Airlines,Embraer 175||Airbus A320,coach||coach,672,956,None,None,None,2022-04-22T16:48:00.000-07:00,2022-04-22T21:30:00.000-07:00,None,None,None,2022-04-22T18:50:00.000-07:00,2022-04-22T23:59:00.000-07:00,None,None,None,SEA,ONT,None,None,None,OAK,SEA,None,None,None,Alaska Airlines,Alaska Airlines,None,None,None,Embraer 175,Airbus A320,None,None,None,coach,coach,None,None,None,16:48:00.000,21:30:00.000,None,None,None,18:50:00.000,23:59:00.000,None,None,None
3,2022-04-17,2022-05-18,LGA,SFO,PT10H22M,0,0,0,0,440.93,497.6,9,762||2135,2022-05-18T16:10:00.000-04:00||2022-05-18T21:2...,2022-05-18T18:47:00.000-04:00||2022-05-18T23:3...,ATL||SFO,LGA||ATL,Delta||Delta,Airbus A321||Boeing 757-300,coach||coach,762,2135,None,None,None,2022-05-18T16:10:00.000-04:00,2022-05-18T21:22:00.000-04:00,None,None,None,2022-05-18T18:47:00.000-04:00,2022-05-18T23:32:00.000-07:00,None,None,None,ATL,SFO,None,None,None,LGA,ATL,None,None,None,Delta,Delta,None,None,None,Airbus A321,Boeing 757-300,None,None,None,coach,coach,None,None,None,16:10:00.000,21:22:00.000,None,None,None,18:47:00.000,23:32:00.000,None,None,None
4,2022-04-17,2022-05-06,SFO,BOS,PT8H29M,1,0,0,0,506.05,567.6,3,2566||185,2022-05-06T21:52:00.000-07:00||2022-05-07T08:0...,2022-05-07T06:30:00.000-04:00||2022-05-07T09:2...,JFK||BOS,SFO||JFK,JetBlue Airways||JetBlue Airways,Airbus A319-321||AIRBUS INDUSTRIE A321 SHARKLETS,coach||coach,2566,185,None,None,None,2022-05-06T21:52:00.000-07:00,2022-05-07T08:05:00.000-04:00,None,None,None,2022-05-07T06:30:00.000-04:00,2022-05-07T09:21:00.000-04:00,None,None,None,JFK,BOS,None,None,None,SFO,JFK,None,None,None,JetBlue Airways,JetBlue Airways,None,None,None,Airbus A319-321,AIRBUS INDUSTRIE A321 SHARKLETS,None,None,None,coach,coach,None,None,None,21:52:00.000,08:05:00.000,None,None,None,06:30:00.000,09:21:00.000,None,None,None

### Select most useful features again

searchDate, flightDate, startingAirport, destinationAirport, travelDuration, elapsedDays, isBasicEconomy, isRefundable, isNonStop, baseFare, totalFare, seatsRemaining, 1segDistance, 2segDistance, 3segDistance, 4segDistance, 5segDistance, 1depTimeOnly, 2depTimeOnly, 3depTimeOnly, 4depTimeOnly, 5depTimeOnly, 1arrTimeOnly, 2arrTimeOnly, 3arrTimeOnly, 4arrTimeOnly, 5arrTimeOnly, 1arrAirport, 2arrAirport, 3arrAirport, 4arrAirport, 5arrAirport, 1depAirport, 2depAirport, 3depAirport, 4depAirport, 5depAirport, 1airline, 2airline, 3airline, 4airline, 5airline, 1equipment, 2equipment, 3equipment, 4equipment, 5equipment, 1cabin, 2cabin, 3cabin, 4cabin, 5cabin.

In [118]:
even_more_useful_feat_data = useful_features_data[['searchDate', 'flightDate', 'startingAirport', 'destinationAirport', 'travelDuration', 'elapsedDays', 'isBasicEconomy', 'isRefundable', 'isNonStop', 'baseFare', 'totalFare', 'seatsRemaining', '1segDistance', '2segDistance', '3segDistance', '4segDistance', '5segDistance', '1depTimeOnly', '2depTimeOnly', '3depTimeOnly', '4depTimeOnly', '5depTimeOnly', '1arrTimeOnly', '2arrTimeOnly', '3arrTimeOnly', '4arrTimeOnly', '5arrTimeOnly', '1arrAirport', '2arrAirport', '3arrAirport', '4arrAirport', '5arrAirport', '1depAirport', '2depAirport', '3depAirport', '4depAirport', '5depAirport', '1airline', '2airline', '3airline', '4airline', '5airline', '1equipment', '2equipment', '3equipment', '4equipment', '5equipment', '1cabin', '2cabin', '3cabin', '4cabin', '5cabin']]

In [119]:
even_more_useful_feat_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4106938 entries, 0 to 4106937
Data columns (total 52 columns):
 #   Column              Dtype
---  ------              -----
 0   searchDate          object
 1   flightDate          object
 2   startingAirport     object
 3   destinationAirport  object
 4   travelDuration      object
 5   elapsedDays         int64
 6   isBasicEconomy      int64
 7   isRefundable        int64
 8   isNonStop           int64
 9   baseFare            float64
 10  totalFare           float64
 11  seatsRemaining      int64
 12  1segDistance        object
 13  2segDistance        object
 14  3segDistance        object
 15  4segDistance        object
 16  5segDistance        object
 17  1depTimeOnly        object
 18  2depTimeOnly        object
 19  3depTimeOnly        object
 20  4depTimeOnly        object
 21  5depTimeOnly        object
 22  1arrTimeOnly        object
 23  2arrTimeOnly        object
 24  3arrTimeOnly        object
 25  4arrTimeOnly        object
 26  5arrTimeOnly        object
 27  1arrAirport         object
 28  2arrAirport         object
 29  3arrAirport         object
 30  4arrAirport         object
 31  5arrAirport         object
 32  1depAirport         object
 33  2depAirport         object
 34  3depAirport         object
 35  4depAirport         object
 36  5depAirport         object
 37  1airline            object
 38  2airline            object
 39  3airline            object
 40  4airline            object
 41  5airline            object
 42  1equipment          object
 43  2equipment          object
 44  3equipment          object
 45  4equipment          object
 46  5equipment          object
 47  1cabin              object
 48  2cabin              object
 49  3cabin              object
 50  4cabin              object
 51  5cabin              object
dtypes: float64(2), int64(5), object(45)
memory usage: 1.6+ GB

In [120]:
even_more_useful_feat_data.head()

,searchDate,flightDate,startingAirport,destinationAirport,travelDuration,elapsedDays,isBasicEconomy,isRefundable,isNonStop,baseFare,totalFare,seatsRemaining,1segDistance,2segDistance,3segDistance,4segDistance,5segDistance,1depTimeOnly,2depTimeOnly,3depTimeOnly,4depTimeOnly,5depTimeOnly,1arrTimeOnly,2arrTimeOnly,3arrTimeOnly,4arrTimeOnly,5arrTimeOnly,1arrAirport,2arrAirport,3arrAirport,4arrAirport,5arrAirport,1depAirport,2depAirport,3depAirport,4depAirport,5depAirport,1airline,2airline,3airline,4airline,5airline,1equipment,2equipment,3equipment,4equipment,5equipment,1cabin,2cabin,3cabin,4cabin,5cabin
0,2022-04-17,2022-04-21,LGA,DFW,PT5H45M,0,1,0,0,110.70,142.6,9,762,725,None,None,None,08:00:00.000,11:23:00.000,None,None,None,10:29:00.000,12:45:00.000,None,None,None,ATL,DFW,None,None,None,LGA,ATL,None,None,None,Delta,Delta,None,None,None,Airbus A321,Airbus A321,None,None,None,coach,coach,None,None,None
1,2022-04-18,2022-04-24,ATL,LGA,PT2H22M,0,0,0,1,450.23,498.6,1,762,None,None,None,None,20:10:00.000,None,None,None,None,22:32:00.000,None,None,None,None,LGA,None,None,None,None,ATL,None,None,None,None,American Airlines,None,None,None,None,Embraer 170,None,None,None,None,coach,None,None,None,None
2,2022-04-17,2022-04-22,OAK,LAX,PT7H11M,0,0,0,0,645.02,717.0,7,672,956,None,None,None,16:48:00.000,21:30:00.000,None,None,None,18:50:00.000,23:59:00.000,None,None,None,SEA,ONT,None,None,None,OAK,SEA,None,None,None,Alaska Airlines,Alaska Airlines,None,None,None,Embraer 175,Airbus A320,None,None,None,coach,coach,None,None,None
3,2022-04-17,2022-05-18,LGA,SFO,PT10H22M,0,0,0,0,440.93,497.6,9,762,2135,None,None,None,16:10:00.000,21:22:00.000,None,None,None,18:47:00.000,23:32:00.000,None,None,None,ATL,SFO,None,None,None,LGA,ATL,None,None,None,Delta,Delta,None,None,None,Airbus A321,Boeing 757-300,None,None,None,coach,coach,None,None,None
4,2022-04-17,2022-05-06,SFO,BOS,PT8H29M,1,0,0,0,506.05,567.6,3,2566,185,None,None,None,21:52:00.000,08:05:00.000,None,None,None,06:30:00.000,09:21:00.000,None,None,None,JFK,BOS,None,None,None,SFO,JFK,None,None,None,JetBlue Airways,JetBlue Airways,None,None,None,Airbus A319-321,AIRBUS INDUSTRIE A321 SHARKLETS,None,None,None,coach,coach,None,None,None

### Times: if 8:30 round up to 9, if 1:15 round down to 1 etc

In [88]:
# numerical and 00 to 24. And if it is 1:30 we either get 1 or 2.

### Add columns (check which ones with distance, duration etc)

Difference between total and base fare to see extra money paid in taxes etc, important to create a column that shows the number of segments
, create column "waiting time": difference between first segment arrival and second segment departure, distance: how do we make the difference between the second and first segment??? When we have up to 5???

In [89]:
''' data_from_db[data_from_db["elapsedDays"] > 1] ''' # to return values >1 in the elapsedDays column

' data_from_db[data_from_db["elapsedDays"] > 1] '

In [91]:
#convert searchDate column to a date, so that we can filter months

# isBasicEconomy, isRefundable, isNonStop -> check how useful they are
# check if travelDuration or totalTravelDistance have a higher impact on flight: distance could make the price higher
# totalTravelDistance is already numerical: don't have to convert it
# segmentsArrivalAirportCode: check relevance
# segmentsEquipmentDescription: check if useful
# find out what are the categories in segmentsCabinCode

In [92]:
# segments: we can take first segment departure, second seg dep, first seg arrival and second arrival in different columns (maybe price is influenced by the time in between or how late the second dep is etc...)

# convert to datetime when the legs have been separated (easier with non - epoch columns) - use only hours, we want to check the time of the day

How to remove ugly first untitled column???

In [94]:
# print(data_from_db.to_string(index=False))

In [100]:
# Fare basis code: check if it has a high impact
# baseFare: if we only want to predict the ticket price
# totalFare: taxes and so on depends on the area they are flying from and to - !
# isBasicEconomy, isRefundable, isNonStop -> check how useful they are
# check if travelDuration or totalTravelDistance have a higher impact on flight: distance could make the price higher
# totalTravelDistance is already numerical: don't have to convert it
# segmentsArrivalAirportCode: check relevance
# segmentsEquipmentDescription: check if useful
# find out what are the categories in segments cabin code?
#convert searchDate column to a date, so that we can filter months